name: Test Auto Build Size Report

on:
  pull_request_target:
    types: [synchronize, opened]
    paths:
      - 'package.json'

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['analyze']
            })
